import {
  loadConfig,
  middleOutCompress,
  compress,
  middleOutDecompress,
  decompress,
  getWeissmanScore,
  CompressionResult,
  MiddleOutConfig,
  encodeMO,
  decodeMO,
  compressWithMiddleOut,
  decompressWithMiddleOut,
  compressWithRLE,
  decompressWithRLE,
  compressWithSTK,
  decompressWithSTK,
  compressWithTNT,
  decompressWithTNT,
  compressWithZPH,
  decompressWithZPH,
} from "./src";

export {
  loadConfig,
  middleOutCompress,
  compress,
  middleOutDecompress,
  decompress,
  getWeissmanScore,
  CompressionResult,
  MiddleOutConfig,
  encodeMO,
  decodeMO,
  compressWithMiddleOut,
  decompressWithMiddleOut,
  compressWithRLE,
  decompressWithRLE,
  compressWithSTK,
  decompressWithSTK,
  compressWithTNT,
  decompressWithTNT,
  compressWithZPH,
  decompressWithZPH,
};

loadConfig();
